#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import struct
import base64
import string
import platform
import argparse
import pprint
from pyparsing import *

import otrapps.util
import otrapps
from otrapps.otr_private_key import OtrPrivateKeys
from otrapps.otr_fingerprints import OtrFingerprints
from otrapps.adium import AdiumProperties
from otrapps.gajim import GajimProperties
from otrapps.gibberbot import GibberbotProperties
from otrapps.jitsi import JitsiProperties
from otrapps.irssi import IrssiProperties
from otrapps.pidgin import PidginProperties
from otrapps.gpg import GPGProperties

# TODO merge duplicates in the final keys
# TODO convert protocol names to a standard format, i.e. prpl-jabber vs. libpurple-Jabber
# TODO use python-potr's convertkey.py to convert old libotr files

def testforfile(files):
    islibotr = False
    isotr4j = False

    isjitsi = False
    isgibberbot = False
    isirssi = False
    isadium = False
    ispidgin = False
    isgpg = False

    keys = dict()
    for file in files:
        appdir = os.path.dirname(file)
        print 'Checking ' + appdir + ':'

        if os.path.exists(os.path.join(appdir, 'otr_keystore')):
            isotr4j = True
            isgibberbot = True
        elif os.path.exists(os.path.join(appdir, 'sip-communicator.properties')) \
            and os.path.exists(os.path.join(appdir, 'contactlist.xml')):
            isotr4j = True
            isjitsi = True
        elif os.path.exists(os.path.join(appdir, 'otr.private_key')) \
            and os.path.exists(os.path.join(appdir, 'otr.fingerprints')):
            islibotr = True
            if os.path.exists(os.path.join(appdir, 'Accounts.plist')):
                isadium = True
            elif os.path.exists(os.path.join(appdir, 'accounts.xml')):
                ispidgin = True
        elif os.path.exists(os.path.join(appdir, 'otr.key')) \
            and os.path.exists(os.path.join(appdir, 'otr.fp')):
            islibotr = True
            isirssi = True
        elif os.path.exists(os.path.join(appdir, 'secring.gpg')) \
            and os.path.exists(os.path.join(appdir, 'pubring.gpg')):
            isgpg = True

        if isadium:
            print 'Reading Adium files: '
            tmp = AdiumProperties.parse(appdir)
        elif isirssi:
            print 'Reading irssi files: '
            tmp = OtrPrivateKeys.parse(os.path.join(appdir, 'otr.key'))
            keys += OtrFingerprints.parse(os.path.join(appdir, 'otr.fp'))
        elif islibotr:
            print 'Reading libotr files: '
            tmp = OtrPrivateKeys.parse(os.path.join(appdir, 'otr.private_key'))
            tmp += OtrFingerprints.parse(os.path.join(appdir, 'otr.fingerprints'))
        elif isgibberbot:
            print 'Reading Gibberbot otr4j format'
            tmp = GibberbotProperties.parse(os.path.join(appdir, 'otr_keystore'))
            pprint.pprint(tmp)
        elif isjitsi:
            print 'Reading Jitsi otr4j format'
        elif isgpg:
            print 'Reading GnuPG format'

        keys = tmp
            #for k,v in tmp.items():
            #keys[k] = v

    if keys:
        #pprint.pprint(keys)
        if not os.path.exists('output'):
            os.mkdir('output')
        GibberbotProperties.write(keys, 'output')
        OtrFingerprints.write(keys, os.path.join('output', 'otr.fingerprints'))
        OtrPrivateKeys.write(keys, os.path.join('output', 'otr.private_keys'))


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input', action='append',
                        help="specify which programs to take as input: adium, gajim, gibberbot, irssi, jitsi, pidgin (if multiple then they'll be merged)")
    parser.add_argument('-o', '--output', action='append',
                        help="specify which format to write out: all, adium, gajim, gibberbot, irssi, jitsi, pidgin (if multiple then each will be written out)")
    # TODO add --input-folder option, it will conflict with '--input all'
    parser.add_argument('--output-folder', default=os.getcwd(),
                        help='the folder to write the output files to (defaults to current folder)')
    parser.add_argument('--version', action='version', version='%(prog)s 0.1')
    args = parser.parse_args()


    # set defaults
    if not args.input:
        if platform.system() == 'Darwin':
            args.input = ['adium']
        else:
            args.input = ['pidgin']
    if not args.output:
        args.output = ['gibberbot']

    # downcase all names to be a little more friendly
    args.input = [i.lower() for i in args.input]
    args.output = [o.lower() for o in args.output]

    keydict = dict()
    if 'adium' in args.input:
        otrapps.util.merge_keydicts(keydict, AdiumProperties.parse())
    if 'gajim' in args.input:
        otrapps.util.merge_keydicts(keydict, GajimProperties.parse())
    if 'gibberbot' in args.input:
        keyfile = os.path.join(args.output_folder, GibberbotProperties.keyfile)
        if os.path.exists(keyfile):
            otrapps.util.merge_keydicts(keydict, GibberbotProperties.parse(keyfile))
        else:
            print('Gibberbot WARNING: No usable "' + GibberbotProperties.keyfile +
                  '" file found, not reading keys from Gibberbot!')
    if 'jitsi' in args.input:
        otrapps.util.merge_keydicts(keydict, JitsiProperties.parse())
    if 'irssi' in args.input:
        otrapps.util.merge_keydicts(keydict, IrssiProperties.parse())
    if 'pidgin' in args.input:
        otrapps.util.merge_keydicts(keydict, PidginProperties.parse())
    if 'gpg' in args.input:
        otrapps.util.merge_keydicts(keydict, GPGProperties.parse())

    if keydict:
        if not os.path.exists(args.output_folder):
            os.makedirs(args.output_folder)
        if 'all' in args.output:
            AdiumProperties.write(keydict, otrapps.make_outdir(args.output_folder, 'adium'))
            GajimProperties.write(keydict, otrapps.make_outdir(args.output_folder, 'gajim'))
            GibberbotProperties.write(keydict, otrapps.make_outdir(args.output_folder, 'gibberbot'))
            JitsiProperties.write(keydict, otrapps.make_outdir(args.output_folder, 'jitsi'))
            IrssiProperties.write(keydict, otrapps.make_outdir(args.output_folder, 'irssi'))
            PidginProperties.write(keydict, otrapps.make_outdir(args.output_folder, 'pidgin'))
            #GPGProperties.write(keydict, otrapps.make_outdir(args.output_folder, 'gpg'))
        else:
            if 'adium' in args.output:
                AdiumProperties.write(keydict, args.output_folder)
            if 'gajim' in args.output:
                GajimProperties.write(keydict, args.output_folder)
            if 'gibberbot' in args.output:
                GibberbotProperties.write(keydict, args.output_folder)
            if 'jitsi' in args.output:
                JitsiProperties.write(keydict, args.output_folder)
            if 'irssi' in args.output:
                IrssiProperties.write(keydict, args.output_folder)
            if 'pidgin' in args.output:
                PidginProperties.write(keydict, args.output_folder)
            if 'gpg' in args.output:
                GPGProperties.write(keydict, args.output_folder)


if __name__ == "__main__":
    main(sys.argv[1:])
